version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mlflow:
    build: .
    ports:
      - "5001:5000"
    environment:
      BACKEND_STORE_URI: postgresql://mlflow:changeme@postgres:5432/mlflow
      ARTIFACT_ROOT: s3://mlflowtuesday-artifacts/artifacts
      AWS_ACCESS_KEY_ID: ${YC_S3_KEY}
      AWS_SECRET_ACCESS_KEY: ${YC_S3_SECRET}
    depends_on:
      - postgres
    command: mlflow server --backend-store-uri=postgresql://mlflow:changeme@postgres:5432/mlflow --default-artifact-root=s3://mlflowtuesday-artifacts/artifacts --host 0.0.0.0 --port 5000