name: MLflow CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mlflow-test:
    runs-on: ubuntu-latest
    env:
      YC_S3_KEY: ${{ secrets.YC_S3_KEY }}
      YC_S3_SECRET: ${{ secrets.YC_S3_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (для сборки образов)
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start all services
        run: |
          docker-compose up -d --build
        working-directory: .

      - name: Wait for PostgreSQL to be healthy
        run: |
          for i in {1..30}; do
            if docker exec $(docker-compose ps -q postgres) pg_isready -U mlflow; then
              echo "Postgres is ready"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 5
          done
          echo "Postgres did not become ready in time" >&2
          exit 1
        working-directory: .

      - name: Wait for MLflow to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5001/; then
              echo "MLflow is up!"
              exit 0
            fi
            echo "Waiting for MLflow..."
            sleep 5
          done
          echo "MLflow did not start in time" >&2
          exit 1
        working-directory: .

      - name: Run trainer container (train model)
        run: |
          docker-compose run --rm trainer
        working-directory: .

      - name: Tear down docker-compose
        if: always()
        run: docker-compose down -v
        working-directory: .
